platform :ios, '10.0'
project 'CBStudyDemo'
use_frameworks!

target :CBStudyDemo do
   pod 'ReactiveSwift'
   pod 'ReactiveCocoa'
   pod 'RxSwift',    '~> 5'
   pod 'RxCocoa',    '~> 5'
   pod 'SnapKit'
   pod 'HandyJSON', '~>5.0.1'
end
