platform :ios, '10.0'
project 'CBStudyDemo'
use_frameworks!

target :CBStudyDemo do
   pod 'ReactiveSwift'
   pod 'ReactiveCocoa'
   pod 'RxSwift',    '~> 4.0'
   pod 'RxCocoa',    '~> 4.0'
   pod 'SnapKit'
end
